name: Create release 

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'


jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: |
          cargo build --release
          mv target/release/mdzk target/release/mdzk-x86_64-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/mdzk-x86_64-linux
          body: For more information, read the [CHANGELOG](https://github.com/mdzk-rs/mdzk/blob/main/CHANGELOG.md).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
